### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/meta#1]
We need some logo’s, colour hex codes, etc. 

/cc @pitzzz?

**Comment by pitzzz** [comment]
I placed a temp logo in the root folder:

The Lab/00 Assets/01 Visual identity/temp logo file

**Comment by pitzzz** [comment]
<img width="501" alt="180906_the_lab_temp_logo" src="https://user-images.githubusercontent.com/39005087/45143286-22769e80-b1bb-11e8-9500-1152a81337e4.png">

**Comment by wooorm** [comment]
Nice! Is there something that would work well for small and square places, e.g., twitter, or here on GH as [a logo for the organisation](https://github.com/cmda-the-lab)?
