### ISSUE TITLE
Inventorize and categorize practices and materials from the CMD body of knowledge (for lack of better desc.) to test out during the lab.

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/meta#3]

**Comment by Razpudding** [comment]
One of the things to try out during the lab is testing our current practices and materials. I figured I’d start with the onderwijs visie and see if that helps us get an idea of how to work on our first project (when we choose one). What materials/practices would you guys like to test and do you have any idea how to index and structure them?

- What tools do we tell students to use that we might be able to use ourselves (e.g. the methods pack)
- Do root CMD documents like the Vision on Eduction help us while working on our project? How well do they fit our purposes? What do they lack? Which documents
- Which practices and tools that we teach to our students can we apply in our work. How well do they work and how can they be improved/updated (e.g. actor diagram used in Real Time Web)

**Comment by wooorm** [comment]
Method cards ([repo](https://github.com/rouws/cmdmethods) - [demo](http://cmdmethods.nl))

**Comment by pitzzz** [comment]
It might be wise to get back to this issue in two months, when we have a sense of how we work. For now it's important to document our process. Sprint ceremonies are great for documentation, and we can analyze all the information after a couple of sprints to see what methodologies we worked with and how they helped/didnt help to reach our goals.

**Comment by Razpudding** [comment]
Roey and I talked and agreed it's best to use CMD materials as we go along and test them as we go. Then at the end of a sprint we can reflect on which materials were useful. At the end of the project we can summarize which materials were used and what they helped us do (and possible what they failed to help us do).
