### ISSUE TITLE
Discuss with Harry and get confirmation that Florence's project is a valid graduation project

### ISSUE THREAD

**Issue by pitzzz** [cmda-the-lab/meta#5]

**Comment by wooorm** [comment]
@pitzzz This is interesting: a) did you confirm already, and b) could we replicate this to other iterations?

**Comment by pitzzz** [comment]
Yes. Confirmed.

**Comment by pitzzz** [comment]
Harry said that as long as Sonja is on board, he is too. That applies to future projects as well.

**Comment by wooorm** [comment]
Do you have that written down / in an email? May be good, but maybe I’m just stressing though.

**Comment by pitzzz** [comment]
It's fine. I never had a problem with verbal agreements with Harry or Sonja.
